/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "LED_B.h"
#include "LED_B_aliases.h"
#include "LED_G.h"
#include "LED_G_aliases.h"
#include "BTN.h"
#include "BTN_aliases.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "LED_W.h"
#include "LED_W_aliases.h"
#include "ACC_X.h"
#include "ACC_X_aliases.h"
#include "ACC_Y.h"
#include "ACC_Y_aliases.h"
#include "ACC_Z.h"
#include "ACC_Z_aliases.h"
#include "BAT_CELL.h"
#include "BAT_CELL_aliases.h"
#include "Opamp_1.h"
#include "Opamp_2.h"
#include "Opamp_3.h"
#include "Opamp_4.h"
#include "LED_R_1.h"
#include "LED_R_1_aliases.h"
#include "LED_G_1.h"
#include "LED_G_1_aliases.h"
#include "LED_B_1.h"
#include "LED_B_1_aliases.h"
#include "ADC_Done.h"
#include "BTN_ISR.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "BLE_bless_isr.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

